// import "./all_tasks/task1.js";
// import "./all_tasks/task2.js";
// import "./all_tasks/task3.js";
// import "./all_tasks/task4.js";
// import "./all_tasks/task5.js";
// import "./all_tasks/task6.js";
// import "./all_tasks/task7.js";
// import "./all_tasks/task8.js";
// import "./all_tasks/task9.js";
import "./all_tasks/task10.js";